# Services Tier - Backend Microservices
---
# Catalog Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
  namespace: retail-services
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog
  namespace: retail-services
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: mysql
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: catalog-mysql.retail-data:3306
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: catalog
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: retail-services
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: retail-services
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/component: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/component: service
    spec:
      serviceAccountName: catalog
      containers:
        - name: catalog
          envFrom:
            - configMapRef:
                name: catalog
            - secretRef:
                name: catalog-db
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: password
          image: "public.ecr.aws/aws-containers/retail-store-sample-catalog:1.2.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 256m
              memory: 256Mi
---
# Cart Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts
  namespace: retail-services
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carts
  namespace: retail-services
data:
  RETAIL_CART_PERSISTENCE_PROVIDER: dynamodb
  RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME: Items
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: "true"
  AWS_ACCESS_KEY_ID: key
  AWS_SECRET_ACCESS_KEY: secret
  RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT: http://carts-dynamodb.retail-data:8000
---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: retail-services
  labels:
    app.kubernetes.io/name: carts
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: carts
    app.kubernetes.io/component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: retail-services
  labels:
    app.kubernetes.io/name: carts
    app.kubernetes.io/component: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: carts
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: carts
        app.kubernetes.io/component: service
    spec:
      serviceAccountName: carts
      containers:
        - name: carts
          envFrom:
            - configMapRef:
                name: carts
          image: "public.ecr.aws/aws-containers/retail-store-sample-cart:1.2.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 256m
              memory: 256Mi